/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as PalestraRouteImport } from './routes/palestra'
import { Route as PromemoriaRouteImport } from './routes/promemoria'
import { Route as CorsoModuleIdRouteImport } from './routes/corso.$moduleId'
import { Route as PalestraDrillIdRouteImport } from './routes/palestra.$drillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestraRoute = PalestraRouteImport.update({
  id: '/palestra',
  path: '/palestra',
  getParentRoute: () => rootRouteImport,
} as any)
const PromemoriaRoute = PromemoriaRouteImport.update({
  id: '/promemoria',
  path: '/promemoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsoModuleIdRoute = CorsoModuleIdRouteImport.update({
  id: '/corso/$moduleId',
  path: '/corso/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestraDrillIdRoute = PalestraDrillIdRouteImport.update({
  id: '/$drillId',
  path: '/$drillId',
  getParentRoute: () => PalestraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossario': typeof GlossarioRoute
  '/palestra': typeof PalestraRouteWithChildren
  '/promemoria': typeof PromemoriaRoute
  '/corso/$moduleId': typeof CorsoModuleIdRoute
  '/palestra/$drillId': typeof PalestraDrillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossario': typeof GlossarioRoute
  '/palestra': typeof PalestraRouteWithChildren
  '/promemoria': typeof PromemoriaRoute
  '/corso/$moduleId': typeof CorsoModuleIdRoute
  '/palestra/$drillId': typeof PalestraDrillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glossario': typeof GlossarioRoute
  '/palestra': typeof PalestraRouteWithChildren
  '/promemoria': typeof PromemoriaRoute
  '/corso/$moduleId': typeof CorsoModuleIdRoute
  '/palestra/$drillId': typeof PalestraDrillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossario'
    | '/palestra'
    | '/promemoria'
    | '/corso/$moduleId'
    | '/palestra/$drillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossario'
    | '/palestra'
    | '/promemoria'
    | '/corso/$moduleId'
    | '/palestra/$drillId'
  id:
    | '__root__'
    | '/'
    | '/glossario'
    | '/palestra'
    | '/promemoria'
    | '/corso/$moduleId'
    | '/palestra/$drillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlossarioRoute: typeof GlossarioRoute
  PalestraRoute: typeof PalestraRouteWithChildren
  PromemoriaRoute: typeof PromemoriaRoute
  CorsoModuleIdRoute: typeof CorsoModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestra': {
      id: '/palestra'
      path: '/palestra'
      fullPath: '/palestra'
      preLoaderRoute: typeof PalestraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promemoria': {
      id: '/promemoria'
      path: '/promemoria'
      fullPath: '/promemoria'
      preLoaderRoute: typeof PromemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corso/$moduleId': {
      id: '/corso/$moduleId'
      path: '/corso/$moduleId'
      fullPath: '/corso/$moduleId'
      preLoaderRoute: typeof CorsoModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestra/$drillId': {
      id: '/palestra/$drillId'
      path: '/$drillId'
      fullPath: '/palestra/$drillId'
      preLoaderRoute: typeof PalestraDrillIdRouteImport
      parentRoute: typeof PalestraRoute
    }
  }
}

interface PalestraRouteChildren {
  PalestraDrillIdRoute: typeof PalestraDrillIdRoute
}

const PalestraRouteChildren: PalestraRouteChildren = {
  PalestraDrillIdRoute: PalestraDrillIdRoute,
}

const PalestraRouteWithChildren = PalestraRoute._addFileChildren(
  PalestraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlossarioRoute: GlossarioRoute,
  PalestraRoute: PalestraRouteWithChildren,
  PromemoriaRoute: PromemoriaRoute,
  CorsoModuleIdRoute: CorsoModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
